"""Deterministic, local-only redaction for feedback review material."""

from __future__ import annotations

import re
import unicodedata
from dataclasses import dataclass

REDACTOR_VERSION = "redactor-v1"

_SAFE_BLOCKED_TEXT = "[内容已阻断]"
_SAFE_EMPTY_TEXT = "[内容为空]"
_SAFE_UNKNOWN_TEXT = "[未知标识]"
_STOP_NAMES = frozenset(
    {
        "如何",
        "怎么",
        "是否",
        "可以",
        "需要",
        "发生",
        "应该",
        "情况",
        "目前",
        "患者",
        "病人",
        "信息",
        "结果",
    }
)

_ATTACHMENT_RE = re.compile(
    r"(?:\[附件[^\]]*\]|<\s*(?:image|file|attachment)[^>]*>|"
    r"data:(?:image|application)/|(?:^|[\s])[^\s]+\.(?:jpg|jpeg|png|gif|pdf|docx?)\b)",
    re.IGNORECASE,
)
_UNSUPPORTED_RE = re.compile(r"[\ufffd\x00]|(?:无法解析|编码错误|binary payload)", re.IGNORECASE)

_ADDRESS_RE = re.compile(
    r"(?:家庭住址|住址|地址|居住地)\s*[:：]?\s*([^，,。；;\n]{2,80})"
)
_PATIENT_NAME_LABELED_RE = re.compile(
    r"(?:患者姓名|病人姓名|患者名|病人名|姓名)\s*[:：]\s*([一-龥]{2,3})(?=的|目前|应|按|是|在|与|和|[，,。；;\s]|$)"
)
_STAFF_NAME_LABELED_RE = re.compile(
    r"(?:护士姓名|医生姓名|药师姓名|联系人姓名|医护人员姓名|联系人|家属|护士|医生|药师)\s*[:：]\s*([一-龥]{2,3})(?=的|目前|应|按|是|在|与|和|[，,。；;\s]|$)"
)
_PATIENT_NAME_BARE_RE = re.compile(r"(?:患者|病人)([一-龥]{2})")
_STAFF_NAME_BARE_RE = re.compile(r"(?:护士|医生|药师|联系人|家属)([一-龥]{2})")
_CASE_LABEL_RE = re.compile(
    r"(?:病案号|住院号|检查号|病例号|患者编号|就诊号|挂号号)\s*[:：]?\s*([A-Za-z0-9][A-Za-z0-9_-]{3,})"
)
_CASE_PREFIX_RE = re.compile(r"\b(?:MRN|EMR|CASE|ADMISSION)[-_]?[A-Za-z0-9]{4,}\b", re.IGNORECASE)
_BED_RE = re.compile(
    r"(?:床号|床位)\s*[:：]?\s*([A-Za-z0-9一二三四五六七八九十-]{1,12})"
)
_DEVICE_RE = re.compile(
    r"(?:设备编号|设备号|透析机编号|透析机号)\s*[:：]?\s*([A-Za-z0-9_-]{2,20})"
)
_EMAIL_RE = re.compile(r"(?<![\w.+-])[^\s@]+@[^\s@]+\.[A-Za-z]{2,}(?![\w.-])")
_URL_TOKEN_RE = re.compile(
    r"https?://[^\s]+(?:token|access_token|code|key)=[^\s&#]+[^\s]*", re.IGNORECASE
)
_URL_RE = re.compile(r"https?://[^\s]+", re.IGNORECASE)
_TOKEN_RE = re.compile(
    r"(?:\bBearer\s+[A-Za-z0-9._-]{12,}\b|\b(?:sk|key|token)[-_:=][A-Za-z0-9._-]{8,}\b)",
    re.IGNORECASE,
)
_PHONE_RE = re.compile(r"(?<!\d)1[3-9]\d{9}(?!\d)")
_ID_RE = re.compile(r"(?<!\d)(?:\d{17}[\dXx]|\d{15})(?!\d)")
_DATE_RE = re.compile(
    r"(?<!\d)(?:19|20)\d{2}(?:[-/.年]\d{1,2})?(?:[-/.月]\d{1,2}日?)?(?!\d)"
)
_GENERIC_IDENTIFIER_RE = re.compile(
    r"(?<![A-Za-z])[A-Z]{2,8}[-_]?[0-9]{10,}(?![0-9])"
)


@dataclass(frozen=True)
class RedactionResult:
    status: str
    text: str
    flags: tuple[str, ...]
    version: str = REDACTOR_VERSION

    def to_dict(self) -> dict[str, object]:
        return {
            "status": self.status,
            "text": self.text,
            "flags": list(self.flags),
            "version": self.version,
        }


class _RedactionContext:
    def __init__(self) -> None:
        self._placeholders: dict[str, str] = {}
        self._counts: dict[str, int] = {}
        self.flags: list[str] = []

    def placeholder(self, category: str, raw: str) -> str:
        key = unicodedata.normalize("NFKC", raw).strip().casefold()
        if key in self._placeholders:
            placeholder = self._placeholders[key]
        else:
            self._counts[category] = self._counts.get(category, 0) + 1
            index = self._counts[category]
            label = {
                "patient_name": "患者",
                "staff_name": "人员",
            }.get(category, category)
            placeholder = f"[{label}-{index}]" if category in {"patient_name", "staff_name"} else f"[{label}]"
            self._placeholders[key] = placeholder
        if category not in self.flags:
            self.flags.append(category)
        return placeholder


def _replace(pattern: re.Pattern[str], text: str, context: _RedactionContext, category: str, group: int = 0) -> str:
    def replacement(match: re.Match[str]) -> str:
        raw = match.group(group)
        return context.placeholder(category, raw)

    return pattern.sub(replacement, text)


def contains_unredacted_identifier(text: str) -> bool:
    """Return whether final text still contains a direct identifier pattern."""

    if not isinstance(text, str):
        return True
    # Placeholders are generated by this module and are intentionally safe;
    # do not scan their labels (for example ``[case_number]``) as raw IDs.
    scan_text = re.sub(r"\[[^\]]+\]", "", text)
    patterns = (
        _PHONE_RE,
        _ID_RE,
        _EMAIL_RE,
        _CASE_PREFIX_RE,
        _CASE_LABEL_RE,
        _BED_RE,
        _DEVICE_RE,
        _URL_TOKEN_RE,
        _TOKEN_RE,
        _GENERIC_IDENTIFIER_RE,
    )
    return any(pattern.search(scan_text) is not None for pattern in patterns)


def _redact_with_context(value: object, context: _RedactionContext) -> RedactionResult:
    if not isinstance(value, str):
        return RedactionResult("blocked", _SAFE_BLOCKED_TEXT, ("invalid_input",))
    text = unicodedata.normalize("NFKC", value).strip()
    if not text:
        return RedactionResult("review_required", _SAFE_EMPTY_TEXT, ("empty_text",))

    if _ATTACHMENT_RE.search(text):
        return RedactionResult("blocked", _SAFE_BLOCKED_TEXT, ("attachment",))

    status = "passed"
    if _UNSUPPORTED_RE.search(text):
        status = "review_required"
        context.flags.append("unsupported_encoding")
        text = _UNSUPPORTED_RE.sub(_SAFE_UNKNOWN_TEXT, text)

    # Remove an unlabelled long identifier before narrower rules (such as an
    # ID-number suffix) can split it and accidentally make the remainder look
    # safe.
    if _GENERIC_IDENTIFIER_RE.search(text):
        status = "review_required"
        context.flags.append("unresolved_identifier")
        text = _GENERIC_IDENTIFIER_RE.sub(_SAFE_UNKNOWN_TEXT, text)

    text = _replace(_ADDRESS_RE, text, context, "address", 1)
    text = _replace(_STAFF_NAME_LABELED_RE, text, context, "staff_name", 1)
    # Run staff-specific labels before the generic ``姓名`` patient rule so
    # that labels such as ``药师姓名`` are classified as staff identifiers.
    text = _replace(_PATIENT_NAME_LABELED_RE, text, context, "patient_name", 1)

    def bare_name_replacement(category: str):
        def replacement(match: re.Match[str]) -> str:
            raw = match.group(1)
            if raw in _STOP_NAMES:
                return match.group(0)
            return match.group(0)[: len(match.group(0)) - len(raw)] + context.placeholder(category, raw)

        return replacement

    text = _PATIENT_NAME_BARE_RE.sub(bare_name_replacement("patient_name"), text)
    text = _STAFF_NAME_BARE_RE.sub(bare_name_replacement("staff_name"), text)
    text = _replace(_CASE_LABEL_RE, text, context, "case_number", 1)
    text = _replace(_CASE_PREFIX_RE, text, context, "case_number")
    text = _replace(_BED_RE, text, context, "bed_number", 1)
    text = _replace(_DEVICE_RE, text, context, "device_number", 1)
    text = _replace(_EMAIL_RE, text, context, "email")
    text = _replace(_URL_TOKEN_RE, text, context, "token")
    text = _replace(_TOKEN_RE, text, context, "token")
    text = _replace(_URL_RE, text, context, "contact")
    text = _replace(_PHONE_RE, text, context, "phone")
    text = _replace(_ID_RE, text, context, "id_number")
    text = _replace(_DATE_RE, text, context, "date")

    if contains_unredacted_identifier(text):
        status = "review_required"
        if "unresolved_identifier" not in context.flags:
            context.flags.append("unresolved_identifier")
        text = _GENERIC_IDENTIFIER_RE.sub(_SAFE_UNKNOWN_TEXT, text)
        text = _CASE_PREFIX_RE.sub(_SAFE_UNKNOWN_TEXT, text)
        text = _URL_TOKEN_RE.sub(_SAFE_UNKNOWN_TEXT, text)
        text = _TOKEN_RE.sub(_SAFE_UNKNOWN_TEXT, text)
        text = _EMAIL_RE.sub(_SAFE_UNKNOWN_TEXT, text)
        text = _PHONE_RE.sub(_SAFE_UNKNOWN_TEXT, text)
        text = _ID_RE.sub(_SAFE_UNKNOWN_TEXT, text)
        text = _BED_RE.sub(_SAFE_UNKNOWN_TEXT, text)
        text = _DEVICE_RE.sub(_SAFE_UNKNOWN_TEXT, text)

    if status != "passed":
        final_status = status
    else:
        final_status = "passed"
    flags = tuple(dict.fromkeys(context.flags))
    return RedactionResult(final_status, text, flags)


def redact_text(text: str, *, entity_scope: str = "interaction") -> RedactionResult:
    """Redact one text value without writing or sending the original."""

    if entity_scope not in {"interaction", "message"}:
        raise ValueError("entity_scope is invalid")
    return _redact_with_context(text, _RedactionContext())


def redact_interaction(
    question: str, answer: str
) -> tuple[RedactionResult, RedactionResult, tuple[str, ...]]:
    """Redact question and answer with one in-memory placeholder map."""

    context = _RedactionContext()
    question_result = _redact_with_context(question, context)
    answer_result = _redact_with_context(answer, context)
    flags = tuple(dict.fromkeys((*question_result.flags, *answer_result.flags, *context.flags)))
    return (
        RedactionResult(question_result.status, question_result.text, flags),
        RedactionResult(answer_result.status, answer_result.text, flags),
        flags,
    )
